'use strict';
let settings={};
async function load(){const data=await chrome.runtime.sendMessage({type:'state'});if(!data?.ok)throw new Error(data?.message||'Reload the extension.');settings=data.settings;document.getElementById('destination').textContent=settings.repository?`${settings.githubUser?.login?'@'+settings.githubUser.login+' · ':''}${settings.repository}`:settings.githubUser?`@${settings.githubUser.login} · Select a repository in workspace.`:'Connect GitHub to get started.';document.getElementById('done').textContent=data.items.filter(x=>['synced','unchanged'].includes(x.status)).length;document.getElementById('waiting').textContent=data.items.filter(x=>['queued','retrying','syncing'].includes(x.status)).length;document.getElementById('failed').textContent=data.items.filter(x=>x.status==='failed').length;document.getElementById('toggle').textContent=settings.paused?'Resume sync':'Pause sync';document.getElementById('connect').textContent=settings.githubUser?'Reconnect GitHub ↗':'Connect GitHub ↗';}
const error=e=>document.getElementById('message').textContent=e.message;
async function connect(){try{const button=document.getElementById('connect');button.disabled=true;document.getElementById('message').textContent='Opening GitHub authorization…';const r=await chrome.runtime.sendMessage({type:'connectGitHub'});if(!r.ok)throw new Error(r.message);const repos=await chrome.runtime.sendMessage({type:'getRepos'});if(!repos.ok)throw new Error(repos.message);if(!repos.repositories.length)throw new Error('No accessible GitHub repositories found. Create or get access to a repository first.');const names=repos.repositories.map(x=>x.fullName);const choice=prompt(`GitHub connected as @${r.user.login}.\n\nEnter the repository number to use:\n\n${names.map((x,i)=>`${i+1}. ${x}`).join('\n')}`,'1');if(choice===null)return;const index=Number(choice)-1;if(!Number.isInteger(index)||!repos.repositories[index])throw new Error('Invalid repository selection.');const selected=repos.repositories[index];const selectedResult=await chrome.runtime.sendMessage({type:'selectRepository',repository:selected,branch:'',folder:'LeetCode'});if(!selectedResult.ok)throw new Error(selectedResult.message);document.getElementById('message').textContent=`Connected to ${selected.fullName}.`;await load();}catch(e){error(e);}finally{document.getElementById('connect').disabled=false;}}
document.getElementById('connect').onclick=connect;
document.getElementById('open').onclick=()=>chrome.runtime.openOptionsPage();
document.getElementById('toggle').onclick=async()=>{try{const r=await chrome.runtime.sendMessage({type:'pause',paused:!settings.paused});if(!r.ok)throw new Error(r.message);await load();}catch(e){error(e);}};
chrome.storage.onChanged.addListener(()=>load().catch(error));load().catch(error);
