'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),{once}=require('node:events');
const {createServer,loadConfig}=require('../oauth-service/app');
const id='a'.repeat(32),config={clientId:'test-client-id',clientSecret:'test-only-secret-for-fixtures',extensionIds:[id]};
async function start(t,fetchImpl){const server=createServer(config,{fetchImpl});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));});return `http://127.0.0.1:${server.address().port}`;}
const headers={Origin:`chrome-extension://${id}`,'Content-Type':'application/json'};
const body={code:'authorization-code',codeVerifier:'v'.repeat(43),redirectUri:`https://${id}.chromiumapp.org/github`};
test('broker keeps secret server-side and forwards verifier, returning only token fields',async t=>{const base=await start(t,async(url,o)=>{assert.equal(url,'https://github.com/login/oauth/access_token');const p=new URLSearchParams(o.body);assert.equal(p.get('client_secret'),config.clientSecret);assert.equal(p.get('code_verifier'),body.codeVerifier);assert.equal(o.redirect,'error');return new Response(JSON.stringify({access_token:'test-only-token',token_type:'bearer',scope:'repo',debug:config.clientSecret}));});const r=await fetch(base+'/oauth/exchange',{method:'POST',headers,body:JSON.stringify(body)});assert.equal(r.status,200);const text=await r.text();assert.ok(!text.includes(config.clientSecret));assert.ok(!text.includes('debug'));assert.equal(r.headers.get('cache-control'),'no-store');});
test('broker rejects wrong origin, callback, missing verifier and malformed JSON without GitHub calls',async t=>{const base=await start(t,()=>assert.fail('Must not contact provider'));for(const origin of ['https://evil.test','null',`chrome-extension://${'b'.repeat(32)}`])assert.equal((await fetch(base+'/oauth/exchange',{method:'POST',headers:{...headers,Origin:origin},body:JSON.stringify(body)})).status,403);for(const b of [{...body,redirectUri:'https://evil.test/'},{...body,codeVerifier:''}])assert.equal((await fetch(base+'/oauth/exchange',{method:'POST',headers,body:JSON.stringify(b)})).status,400);assert.equal((await fetch(base+'/oauth/exchange',{method:'POST',headers,body:'{'})).status,400);});
test('refresh and revoke use fixed provider endpoints without logging or echoing secrets',async t=>{const calls=[];const base=await start(t,async(url,o)=>{calls.push({url,o});return o.method==='DELETE'?new Response(null,{status:204}):new Response(JSON.stringify({access_token:'test-new-access',token_type:'bearer',scope:'repo',refresh_token:'test-new-refresh'}));});assert.equal((await fetch(base+'/oauth/refresh',{method:'POST',headers,body:JSON.stringify({refreshToken:'test-old-refresh'})})).status,200);assert.equal(new URLSearchParams(calls[0].o.body).get('grant_type'),'refresh_token');assert.equal((await fetch(base+'/oauth/revoke',{method:'POST',headers,body:JSON.stringify({accessToken:'test-new-access'})})).status,200);assert.match(calls[1].url,/\/applications\/test-client-id\/token$/);});
test('provider errors are sanitized and no client-supplied secret can override application config',async t=>{const base=await start(t,async()=>new Response(JSON.stringify({error:'bad_verification_code',error_description:config.clientSecret})));const r=await fetch(base+'/oauth/exchange',{method:'POST',headers,body:JSON.stringify({...body,client_secret:'attacker'})});assert.equal(r.status,401);assert.ok(!(await r.text()).includes(config.clientSecret));});
test('missing publisher credentials fail startup',()=>{assert.throws(()=>loadConfig({}));assert.throws(()=>loadConfig({GITHUB_CLIENT_ID:'test-client',GITHUB_CLIENT_SECRET:'s'.repeat(30),EXTENSION_IDS:'invalid'}));});
