'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const G=require('../extension/github');
const repo={id:12,owner:{login:'owner'},name:'solutions',full_name:'owner/solutions',default_branch:'main',permissions:{push:true}};
function mock(data){const calls=[];return {calls,request:async(p,o={})=>{calls.push({p,...o});assert.ok(data.length,'Unexpected call');return data.shift();}};}
const settings={target:'t',repoId:'12',branch:'main',folder:'LeetCode'},item={target:'t',repoId:'12',userId:'7',code:'// नमस्ते\n\treturn 1;\n',slug:'two-sum',title:'Two Sum',language:'cpp',difficulty:'Easy',submissionId:'1'};
test('lists only writable non-archived repos and excludes private repos without scope',async()=>{const m=mock([[repo,{...repo,id:13,private:true},{...repo,id:14,archived:true},{...repo,id:15,permissions:{push:false}}]]);assert.deepEqual((await G.listRepositories(m.request,1,false)).repositories.map(r=>r.id),['12']);});
test('repository pagination reports next page even when current page is filtered out',async()=>{const m=mock([Array.from({length:100},(_,i)=>({...repo,id:i+1,archived:true}))]);const r=await G.listRepositories(m.request,1);assert.equal(r.repositories.length,0);assert.equal(r.nextPage,2);});
test('destination fingerprints include numeric account, repo ID, branch and folder',async()=>{const a=await G.destination(mock([repo,{}]).request,'7','12','main','LeetCode'),b=await G.destination(mock([repo,{}]).request,'8','12','main','LeetCode');assert.notEqual(a.target,b.target);assert.equal(a.repoId,'12');await assert.rejects(G.destination(mock([repo]).request,'7','12','main','../escape'));});
test('creates exact UTF-8 code on selected branch and original repo ID',async()=>{const m=mock([repo,null,{content:{html_url:'https://github.com/owner/solutions'}}]);assert.equal((await G.sync(m.request,settings,item,'7')).action,'created');assert.equal(m.calls[0].p,'/repositories/12');assert.equal(m.calls[2].body.branch,'main');assert.equal(G.fromBase64(m.calls[2].body.content),item.code);});
test('identical code avoids a duplicate commit',async()=>{const m=mock([repo,{type:'file',sha:'abc',encoding:'base64',content:G.utf8base64(item.code)}]);assert.equal((await G.sync(m.request,settings,item,'7')).action,'unchanged');assert.equal(m.calls.length,2);});
test('updates using the fresh SHA and preserves repository rename',async()=>{const m=mock([{...repo,name:'renamed',full_name:'owner/renamed'},{type:'file',sha:'fresh',encoding:'base64',content:G.utf8base64('old')},{content:{}}]);assert.equal((await G.sync(m.request,settings,item,'7')).action,'updated');assert.equal(m.calls[2].body.sha,'fresh');assert.match(m.calls[2].p,/owner\/renamed/);});
test('account or destination mismatch cannot issue requests',async()=>{for(const patch of [{userId:'8'},{target:'other'},{repoId:'999'}])await assert.rejects(G.sync(()=>assert.fail('No request allowed'),settings,{...item,...patch},'7'));});
test('GitHub client does not forward OAuth token to redirects and handles real HTTP failures',async()=>{const r=G.client(async()=> 'test-only-token',async(url,o)=>{assert.equal(url,'https://api.github.com/user');assert.equal(o.redirect,'error');assert.equal(o.credentials,'omit');return new Response('{}',{status:401});});await assert.rejects(r('/user'),e=>e.status===401&&!e.retryable);await assert.rejects(r('//evil.test'));});
test('rate limits and SHA conflicts retry; permission failures do not',()=>{assert.equal(G.githubError(new Response('{}',{status:409})).retryable,true);assert.equal(G.githubError(new Response('{}',{status:403})).retryable,false);assert.ok(G.githubError(new Response('{}',{status:403,headers:{'retry-after':'120'}})).retryAfter>=120);});
