'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const O=require('../extension/oauth');
const id='a'.repeat(32),config={clientId:'client-test-123',extensionId:id,brokerOrigin:'https://auth.example.test'};
function harness(mode='ok'){
 const store={},calls=[];let challenge;
 const chrome={runtime:{id},identity:{getRedirectURL:()=>`https://${id}.chromiumapp.org/github`,launchWebAuthFlow:async({url})=>{const u=new URL(url);challenge=u.searchParams.get('code_challenge');assert.equal(u.hostname,'github.com');assert.equal(u.searchParams.get('code_challenge_method'),'S256');assert.ok(!url.includes('secret'));return `https://${id}.chromiumapp.org/github?code=test-code&state=${mode==='state'?'wrong':u.searchParams.get('state')}${mode==='denied'?'&error=access_denied':''}`;}},storage:{session:{set:async x=>Object.assign(store,x),get:async()=>({...store}),remove:async k=>delete store[k]}}};
 const fetchImpl=async(url,options)=>{calls.push({url,options});if(url.endsWith('/oauth/exchange')){const b=JSON.parse(options.body),hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(b.codeVerifier));assert.equal(Buffer.from(hash).toString('base64url'),challenge);assert.equal(b.redirectUri,chrome.identity.getRedirectURL());return new Response(JSON.stringify({access_token:'test-only-access',token_type:'bearer',scope:'public_repo,read:user',refresh_token:'test-only-refresh',expires_in:28800}));}if(url.endsWith('/user'))return new Response(JSON.stringify({id:7,login:'akash'}));return new Response('{}');};
 return {chrome,fetchImpl,store,calls};
}
test('PKCE creates unique verifiers and matching S256 challenges',async()=>{const a=await O.pkce(),b=await O.pkce();assert.equal(a.verifier.length,43);assert.notEqual(a.verifier,b.verifier);assert.equal(Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(a.verifier))).toString('base64url'),a.challenge);});
test('authorization validates state, exchanges code with PKCE and identifies account',async()=>{const h=harness();const a=await O.authorize(config,h.chrome,false,h.fetchImpl);assert.equal(a.user.id,'7');assert.equal(a.user.login,'akash');assert.equal(a.status,'connected');assert.equal(h.store.oauthPending,undefined);assert.equal(h.calls.length,2);});
test('forged OAuth state never reaches token exchange',async()=>{const h=harness('state');await assert.rejects(O.authorize(config,h.chrome,false,h.fetchImpl),/verification failed/);assert.equal(h.calls.length,0);assert.equal(h.store.oauthPending,undefined);});
test('declined OAuth authorization leaves no pending state',async()=>{const h=harness('denied');await assert.rejects(O.authorize(config,h.chrome,false,h.fetchImpl),/declined/);assert.equal(h.calls.length,0);});
test('callback is bound to exact origin, path and single state/code values',()=>{const callback=`https://${id}.chromiumapp.org/github`;for(const u of [`${callback}?code=c&state=s&state=s`,`${callback}?code=c&code=d&state=s`,`${callback}/extra?code=c&state=s`,`${callback}?code=c&state=s#token=x`,'https://evil.test/github?code=c&state=s'])assert.throws(()=>O.validateCallback(u,callback,'s'));});
test('release config fails closed for missing IDs, mismatched extension and HTTP broker',()=>{assert.throws(()=>O.checkConfig({},id));assert.throws(()=>O.checkConfig({...config,extensionId:'b'.repeat(32)},id));assert.throws(()=>O.checkConfig({...config,brokerOrigin:'http://auth.example.test'},id));assert.throws(()=>O.checkConfig({...config,brokerOrigin:'https://auth.example.test/path'},id));});
test('token responses require bearer type and repository scope',()=>{assert.throws(()=>O.credentials({access_token:'test',token_type:'bearer',scope:'read:user'}));assert.throws(()=>O.credentials({access_token:'test',token_type:'basic',scope:'repo'}));assert.equal(O.credentials({access_token:'test',token_type:'bearer',scope:'repo'}).refreshToken,'');});
