'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {validateSubmission,syncSubmission,filePath,githubError}=require('../server/sync');
const {loadConfig}=require('../server/config');
const config=loadConfig({GITHUB_TOKEN:'test-token',GITHUB_OWNER:'tester',GITHUB_REPO:'solutions',AUTOSYNC_KEY:'x'.repeat(48),GITHUB_BRANCH:'practice'});
const input={slug:'two-sum',title:'Two Sum',difficulty:'Easy',language:'cpp',code:'// नमस्ते\nclass Solution {};\n',submissionId:'123',target:config.target};
const response=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers});
function mock(responses){const calls=[];const fetchImpl=async(url,options)=>{calls.push({url,...options});assert.ok(responses.length,'Unexpected GitHub call');return responses.shift();};return {calls,fetchImpl};}
test('validates untrusted inputs and language extensions',()=>{assert.equal(validateSubmission(input).code,input.code);assert.equal(filePath(config,input),'LeetCode/two-sum/cpp/solution.cpp');assert.equal(filePath(config,{...input,language:'python3'}),'LeetCode/two-sum/python3/solution.py');for(const patch of [{slug:'../secret'},{code:' '},{code:'😀'.repeat(60000)},{language:'__proto__'},{title:'a\nb'},{submissionId:'abc'},{difficulty:'Impossible'}])assert.throws(()=>validateSubmission({...input,...patch}));});
test('creates UTF-8 solution in the configured branch',async()=>{const m=mock([response({},404),response({content:{html_url:'https://github.com/tester/solutions/blob/practice/x'}},201)]);const result=await syncSubmission(config,input,m.fetchImpl);assert.equal(result.action,'created');assert.match(m.calls[0].url,/\?ref=practice$/);const body=JSON.parse(m.calls[1].body);assert.equal(Buffer.from(body.content,'base64').toString('utf8'),input.code);assert.equal(body.branch,'practice');assert.equal(body.sha,undefined);});
test('updates existing file using its SHA',async()=>{const m=mock([response({type:'file',sha:'old',encoding:'base64',content:Buffer.from('old code').toString('base64')}),response({content:{}})]);const result=await syncSubmission(config,input,m.fetchImpl);assert.equal(result.action,'updated');assert.equal(JSON.parse(m.calls[1].body).sha,'old');});
test('identical content makes no commit',async()=>{const m=mock([response({type:'file',sha:'abc',encoding:'base64',content:Buffer.from(input.code).toString('base64')})]);assert.equal((await syncSubmission(config,input,m.fetchImpl)).action,'unchanged');assert.equal(m.calls.length,1);});
test('a failed GET is never treated as a missing file',async()=>{for(const status of [401,403,500]){const m=mock([response({},status)]);await assert.rejects(syncSubmission(config,input,m.fetchImpl));assert.equal(m.calls.length,1);}});
test('conflict refreshes SHA before retrying',async()=>{const m=mock([response({type:'file',sha:'one'}),response({},409),response({type:'file',sha:'two'}),response({content:{}})]);assert.equal((await syncSubmission(config,input,m.fetchImpl)).action,'updated');assert.equal(JSON.parse(m.calls[3].body).sha,'two');});
test('rate-limit responses preserve retry timing',()=>{const error=githubError(response({},403,{'retry-after':'120'}));assert.equal(error.retryable,true);assert.ok(error.retryAfter>=120);assert.equal(githubError(response({},403)).retryable,false);});
test('destination mismatch cannot make a GitHub request',async()=>{await assert.rejects(syncSubmission(config,{...input,target:'other'},()=>assert.fail('Must not fetch')),/Destination changed/);});
test('network failures are retryable and do not expose tokens',async()=>{await assert.rejects(syncSubmission(config,input,async()=>{throw new Error(config.token);}),e=>e.retryable&&!e.message.includes(config.token));});
test('configuration rejects invalid destinations and keeps deterministic target identity',()=>{assert.throws(()=>loadConfig({}));assert.notEqual(config.target,loadConfig({GITHUB_TOKEN:'x',GITHUB_OWNER:'tester',GITHUB_REPO:'another',AUTOSYNC_KEY:'a'.repeat(32)}).target);});
