'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const Q=require('../extension/queue'),O=require('../extension/oauth'),G=require('../extension/github');
const source=fs.readFileSync(require.resolve('../extension/background.js'),'utf8'),id='a'.repeat(32);
const user=n=>({id:String(n),login:`user${n}`});
const auth=n=>({user:user(n),sessionId:`session${n}`,accessToken:`test-only-access-${n}`,refreshToken:`test-only-refresh-${n}`,scope:'public_repo',status:'connected',expiresAt:0});
const settings={paused:true,target:'target7',repoId:'12',repository:'owner/solutions',branch:'main',folder:'LeetCode'};
const s={title:'Two Sum',slug:'two-sum',language:'cpp',code:'complete source',difficulty:'Easy',submissionId:'11'};
function harness(initial={},overrides={}){
 const data=structuredClone({schema:3,auth:auth(7),profiles:{7:{settings:{...settings},items:[]}},...initial}),session={};let listener,alarm;
 const area=store=>({setAccessLevel:async()=>{},get:async keys=>Object.fromEntries(keys.map(k=>[k,structuredClone(store[k])])),set:async patch=>Object.assign(store,structuredClone(patch)),remove:async keys=>{for(const k of Array.isArray(keys)?keys:[keys])delete store[k];}});
 const chrome={storage:{local:area(data),session:area(session)},runtime:{id,getURL:()=>`chrome-extension://${id}/`,onInstalled:{addListener:()=>{}},onStartup:{addListener:()=>{}},onMessage:{addListener:f=>listener=f}},action:{setBadgeText:async()=>{},setBadgeBackgroundColor:async()=>{}},alarms:{get:async()=>({}),create:async()=>{},onAlarm:{addListener:f=>alarm=f}}};
 vm.runInNewContext(source,{chrome,importScripts:()=>{},AutoSyncConfig:{clientId:'test-client-id',extensionId:id,brokerOrigin:'https://auth.example.test'},AutoSyncQueue:Q,AutoSyncOAuth:{...O,authorize:async()=>auth(8),broker:async()=>({ok:true}),...overrides.oauth},AutoSyncGitHub:{...G,client:getToken=>G.client(getToken,overrides.fetch||(()=>assert.fail('Unexpected network request'))),...overrides.github},TextEncoder,crypto,console,AbortSignal,fetch:overrides.fetch||(()=>assert.fail('Unexpected network request'))});
 const send=(message,sender={id,url:`chrome-extension://${id}/dashboard.html`})=>new Promise(r=>listener(message,sender,r));
 return {data,send,settle:()=>new Promise(r=>setTimeout(r,35)),alarm:()=>alarm({name:'autosync-retry'})};
}
test('worker state never exposes tokens or another account history',async()=>{const h=harness();await h.send({type:'add',submission:s});const result=await h.send({type:'state'});assert.equal(result.items.length,1);assert.ok(!JSON.stringify(result).includes('test-only'));await h.send({type:'login'});const next=await h.send({type:'state'});assert.equal(next.account.id,'8');assert.equal(next.items.length,0);assert.equal(h.data.profiles[7].items.length,1);});
test('returning to the same numeric account restores its queue and repository',async()=>{const h=harness({}, {oauth:{authorize:async()=>auth(7)}});await h.send({type:'add',submission:s});await h.send({type:'disconnect'});assert.equal((await h.send({type:'state'})).items.length,0);await h.send({type:'login'});assert.equal((await h.send({type:'state'})).items.length,1);});
test('concurrent submissions are serialized and deduplicated',async()=>{const h=harness();const results=await Promise.all([h.send({type:'add',submission:s}),h.send({type:'add',submission:s}),h.send({type:'add',submission:{...s,slug:'second'}})]);assert.ok(results.every(x=>x.ok));assert.equal(h.data.profiles[7].items.length,2);});
test('content scripts cannot read auth, list repos, or change accounts',async()=>{const h=harness(),sender={id,url:'https://leetcode.com/problems/two-sum/',tab:{id:1}};for(const type of ['state','login','repos','disconnect'])assert.equal((await h.send({type},sender)).ok,false);assert.equal((await h.send({type:'capture',submission:s},sender)).ok,true);});
test('offline failures retain source and recover on retry',async()=>{let offline=true;const h=harness({}, {github:{sync:async()=>{if(offline)throw Object.assign(new Error('offline'),{retryable:true});return {action:'created'};}}});await h.send({type:'add',submission:s});await h.send({type:'pause',paused:false});await h.settle();assert.equal(h.data.profiles[7].items[0].status,'retrying');assert.equal(h.data.profiles[7].items[0].code,s.code);offline=false;await h.send({type:'retry'});await h.settle();assert.equal(h.data.profiles[7].items[0].status,'synced');assert.equal(h.data.profiles[7].items[0].code,undefined);});
test('changing account during upload records result only in original account',async()=>{let finish;const h=harness({}, {github:{sync:()=>new Promise(r=>finish=r)}});await h.send({type:'add',submission:s});await h.send({type:'pause',paused:false});await h.settle();await h.send({type:'login'});finish({action:'created'});await h.settle();assert.equal(h.data.profiles[7].items[0].status,'synced');assert.equal(h.data.profiles[8].items.length,0);assert.equal(h.data.auth.user.id,'8');});
test('rotating refresh token is saved and account revalidated before requests',async()=>{let refreshes=0;const h=harness({auth:{...auth(7),expiresAt:1}}, {oauth:{broker:async()=>{refreshes++;return {access_token:'test-new-access',refresh_token:'test-new-refresh',token_type:'bearer',scope:'public_repo',expires_in:28800};},identify:async()=>user(7)},github:{listRepositories:async request=>{await request('/user/repos');return {repositories:[]};}},fetch:async(url,o)=>{assert.equal(o.headers.Authorization,'Bearer test-new-access');return new Response('[]');}});assert.equal((await h.send({type:'repos'})).ok,true);assert.equal(refreshes,1);assert.equal(h.data.auth.refreshToken,'test-new-refresh');});
test('refresh account mismatch expires authentication and never issues repository requests',async()=>{const h=harness({auth:{...auth(7),expiresAt:1}}, {oauth:{broker:async()=>({access_token:'test-new-access',token_type:'bearer',scope:'public_repo'}),identify:async()=>user(8)},github:{listRepositories:async request=>request('/user/repos')}});assert.equal((await h.send({type:'repos'})).ok,false);assert.equal(h.data.auth.status,'expired');assert.equal(h.data.auth.accessToken,undefined);});
test('a cancelled login cannot reconnect after disconnect',async()=>{let finish;const h=harness({}, {oauth:{authorize:()=>new Promise(r=>finish=r)}});const pending=h.send({type:'login'});await h.settle();await h.send({type:'disconnect'});finish(auth(8));assert.equal((await pending).ok,false);assert.equal(h.data.auth,undefined);});
test('v2 migration preserves old queue but removes the pairing key',async()=>{const h=harness({schema:2,settings:{key:'old-private-pairing-key'},items:[s]});await h.send({type:'state'});assert.equal(h.data.legacyV2.items.length,1);assert.equal(h.data.settings,undefined);assert.ok(!JSON.stringify(h.data.legacyV2).includes('old-private'));});
